### ISSUE TITLE
Implement a command to create an e2e test template

### ISSUE THREAD

**Issue by Kaltenbach** [collaborationFactory/cplace-npm-tools#37]
As developer I would like to easily write e2e tests and have a template generated within the right folder structure and the typical imports.

An example would be the angular cli `ng generate ...` command.

A concrete example could be:

```
cplace-cli generate e2e aspect/spec-name --plugin my.fancy.plugin
```

- where `aspect` would be the folder below `plugin/assets/e2e`,
- `spec-name` the bare name of the spec (without ....spec.ts) and 
- `--plugin` defaults to the platform (maybe this could be calculated if the command is run within the plugin's folder)

The file could look like:
```ts
import { callTestSetupHandler } from '../../lib/setup';
import { expect } from 'chai';

describe('On the hello world page', () => {

    before(function() {
        callTestSetupHandler('/test/testHelloWorld');
    });

    it('the logged in user is welcome', () => {
        $('navigate some where').click();
        expect(****).to.equal(true);

        browser.pause(2000); // delete me
    });

});
```

**Comment by Kaltenbach** [comment]
And I really would fancy s.th. like a `describe` and `it` argument to create the spec and test cases...

```
cplace-cli generate e2e aspect/spec-name --describe="On the page" --it="the user can click on button A" --it="and move to another view when clicking on the link"
```

which would generate

```
import { callTestSetupHandler } from '../../lib/setup';
import { expect } from 'chai';

describe('On the page', () => {

    before(function() {
        callTestSetupHandler('/test/testHelloWorld');
    });

    it('the user can click on button A', () => {
        // TODO
    });

    it('and move to another view when clicking on the link', () => {
        // TODO
    });

});
```

**Comment by joachimLengacher** [comment]
If we decided to write the feature specification in the Gherkin language we could use https://github.com/mklabs/mocha-gherkin to translate them to Mocha stubs to achieve what @Kaltenbach requested above. Not sure how much time this really safes though...
